# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/https://github.com/cooperrichard177/cucumber-js-practice.git

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found

      - run: npm install
      - run: npm install cucumber

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: run tests
          command: "./node_modules/.bin/cucumber-js ./features/ -f json:./report/cucumber_report.json"
      - store_test_results:
          path: ./report
      - store_artifacts:
          path: ./report
      # - run:
      #     name: Save test results
      #     command: node index.js
      #     when: always
      # - store_test_results:
      #     path: ~/cucumber
      # - store_artifacts:
      #   path: ~/cucumber
